ECHO_PREFIX="\e["
###############
# Formatting
###############
ECHO_FORMAT_Bold=$ECHO_PREFIX"1m"
ECHO_FORMAT_Dim=$ECHO_PREFIX"2m"
ECHO_FORMAT_Underlined=$ECHO_PREFIX"4m"
ECHO_FORMAT_Blink=$ECHO_PREFIX"5m"
# invert the foreground and background colors
ECHO_FORMAT_Reverse=$ECHO_PREFIX"7m"
# useful for passwords
ECHO_FORMAT_Hidden=$ECHO_PREFIX"8m"
ECHO_FORMAT_Reset=$ECHO_PREFIX"0m"
###############
# 8/16 Colors
# Foreground (text)
###############
ECHO_FG_Default=$ECHO_PREFIX"39m"
ECHO_FG_Black=$ECHO_PREFIX"30m"
ECHO_FG_Red=$ECHO_PREFIX"31m"
ECHO_FG_Green=$ECHO_PREFIX"32m"
ECHO_FG_Yellow=$ECHO_PREFIX"33m"
ECHO_FG_Blue=$ECHO_PREFIX"34m"
ECHO_FG_Magenta=$ECHO_PREFIX"35m"
ECHO_FG_Cyan=$ECHO_PREFIX"36m"
ECHO_FG_LightGray=$ECHO_PREFIX"37m"
ECHO_FG_DarkGray=$ECHO_PREFIX"90m"
ECHO_FG_LightRed=$ECHO_PREFIX"91m"
ECHO_FG_LightGreen=$ECHO_PREFIX"92m"
ECHO_FG_LightYellow=$ECHO_PREFIX"93m"
ECHO_FG_LightBlue=$ECHO_PREFIX"94m"
ECHO_FG_LightMagenta=$ECHO_PREFIX"95m"
ECHO_FG_LightCyan=$ECHO_PREFIX"96m"
ECHO_FG_White=$ECHO_PREFIX"97m"
###############
# 8/16 Colors
# Background (text)
###############
ECHO_BG_Default=$ECHO_PREFIX"49m"
ECHO_BG_Black=$ECHO_PREFIX"40m"
ECHO_BG_Red=$ECHO_PREFIX"41m"
ECHO_BG_Green=$ECHO_PREFIX"42m"
ECHO_BG_Yellow=$ECHO_PREFIX"43m"
ECHO_BG_Blue=$ECHO_PREFIX"44m"
ECHO_BG_Magenta=$ECHO_PREFIX"45m"
ECHO_BG_Cyan=$ECHO_PREFIX"46m"
ECHO_BG_LightGray=$ECHO_PREFIX"47m"
ECHO_BG_DarkGray=$ECHO_PREFIX"100m"
ECHO_BG_LightRed=$ECHO_PREFIX"101m"
ECHO_BG_LightGreen=$ECHO_PREFIX"102m"
ECHO_BG_LightYellow=$ECHO_PREFIX"103m"
ECHO_BG_LightBlue=$ECHO_PREFIX"104m"
ECHO_BG_LightMagenta=$ECHO_PREFIX"105m"
ECHO_BG_LightCyan=$ECHO_PREFIX"106m"
ECHO_BG_White=$ECHO_PREFIX"107m"



ECHO_RESET=${ECHO_BG_Default}${ECHO_FG_Default}${ECHO_FORMAT_Reset}

ECHO_QUESTION=${ECHO_FG_Magenta}
ECHO_PROMT=${ECHO_FG_Magenta}
ECHO_USER_INTERACTION=${ECHO_FG_Magenta}

ECHO_HEADER=${ECHO_FG_LightBlue}
ECHO_INFO=${ECHO_FG_LightYellow}
ECHO_OK=${ECHO_FG_Green}
ECHO_ERROR=${ECHO_FG_Red}
ECHO_WARNING=${ECHO_FG_LightBlue}



















